# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testdemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'CTMediator'

  # Pods for testdemo

  target 'testdemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testdemoUITests' do
    # Pods for testing
  end

end
